### ISSUE TITLE
Update to use english as output language

### ISSUE THREAD

**Issue by drublic** [ysakmrkm/grunt-sass-format#1]
Thanks for what you did here!

Sadly I don't speak Japanese but I'd love to use your work. I think there are a couple of people who feel the same :)
It would be fantastic if you could update the messages to English.

Again, thank you for the work you did.

**Comment by ysakmrkm** [comment]
Thanks for reporting the issue.

I also thought the need for English messages.

so, I'll modify asap.

**Comment by drublic** [comment]
Thanks so much :)

**Comment by ysakmrkm** [comment]
fixed @b9b5ef437b82311fa33ac3e7620173857954777e

Add lang option.
Default is 'en', display message in English.

Please reinstall!
